### ISSUE TITLE
Convert to Open Source?

### ISSUE THREAD

**Issue by DarthOstrich** [DarthOstrich/FoodieShufflePWA#12]
I'm debating if I want to convert this to a public repo.

# Pros
Can use a lot of tools for free (Travis CI)
Can be referenced in articles or for training
If anyone wants a feature and knows how to do it, they can

# Cons
I dunno, something probably.

**Comment by vonetta** [comment]
I think open sourcing is a good idea. People come with great ideaa

**Comment by DarthOstrich** [comment]
Cool. We'll move forward with that in mind.
