### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by DarthOstrich** [DarthOstrich/FoodieShufflePWA#8]
Need some SEO up in this thing.

**Comment by DarthOstrich** [comment]
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-110013052-2"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-110013052-2');
</script>

**Comment by vonetta** [comment]
how much SEO are you trying to do

**Comment by DarthOstrich** [comment]
I think what we got is good for now.
